AWSTemplateFormatVersion: '2010-09-09'

Description:  "create security groups for ssh and http acces"
Parameters:
  VPC:
    Description: VPC
    Type: String 
  DefaultSecurityGroup:
    Description: Default Security Group of VPC
    Type: String  
  SGName:
    Description: Security Group Name
    Type: String 
    Default: sg-pro2-g16
  SSHLocation:
    Description: the ip address range
    Type: String
    MinLength: 9
    MaxLength: 18
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref 'SSHLocation'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 3000
        ToPort: 3000
        CidrIp: 0.0.0.0/0
    Tags:
      - Key: Name
        Value: !Ref SGName
      - Key: Application
        Value: !Ref "AWS::StackName"

Outputs:
  SecurityGroup:
    Description: Instance Security Group for EC2 Instances
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-SecurityGroup"
