AWSTemplateFormatVersion: '2010-09-09'

Desciption: "create two EC2"
Parameters:
  PublicSubnet:
    Description: Public Subnet
    Type: String
  PrivateSubnet:
    Description: Private Subnet
    Type: String
  SecurityGroup:
    Description: SecurityGroup Name
    Type: String
  KeyName:
    Description: Name of an keypair existing
    Type: AWS::EC2::KeyPair::KeyName
    Default: uattendace-pro1
    ConstraintDescription: must be the name of an existing EC2 KeyPair. 
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro  
    AllowedValues: [t2.micro]
    ConstraintDescription: must be a valid EC2 instance type.
  WebSideAmiId:
    Type: String
    Default: ami-00bcac5ae8c849ed7  #ubuntu 20.04
  EC2WebSite1Name:
    Type: String
    Default: ec2_1_pro2
  EC2WebSite2Name:
    Type: String
    Default: ec2_2_pro2

Resources:
  EC2InstanceWebSite1:
    Type: AWS::EC2:.Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref WebSideAmiId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Ref EC2WebSite1Name
        - Key: Application
          Value: !Ref "AWS::StackName"

  EC2InstanceWebSite2:
    Type: AWS::EC2:.Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref WebSideAmiId
      SubnetId: !Ref PrivateSubnet
      Tags:
        - Key: Name
          Value: !Ref EC2WebSite2Name
        - Key: Application
          Value: !Ref "AWS::StackName"

Outputs:
  EC2WebSite1:
    Description: EC2 WEBSITE
    Value: !Ref EC2InstanceWebSite1
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-EC2Web1"
  EC2WebSite2:
    Description: EC2 WEBSITE
    Value: !Ref EC2InstanceWebSite2
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-EC2Web2"





  