AWSTemplateFormatVersion: '2010-09-09'

Description: "create two EC2"
Parameters:
  PublicSubnet:
    Description: Public Subnet
    Type: String
  PrivateSubnet:
    Description: Private Subnet
    Type: String
  SecurityGroup:
    Description: SecurityGroup Name
    Type: String
  KeyName:
    Description: Name of an keypair existing
    Type: AWS::EC2::KeyPair::KeyName
    Default: uattendace-pro1
    ConstraintDescription: must be the name of an existing EC2 KeyPair. 
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro  
    AllowedValues: [t2.micro]
    ConstraintDescription: must be a valid EC2 instance type.
  WebsideAmiId:
    Type: String
    Default: ami-07efac79022b86107  #ubuntu 20.04
  EC21Name:
    Type: String
    Default: ec2_1_pro2
  EC22Name:
    Type: String
    Default: ec2_2_pro2

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType      
      #SecurityGroups: !Ref SecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref WebsideAmiId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Ref EC21Name
        - Key: Application
          Value: !Ref "AWS::StackName"

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      #SecurityGroups: !Ref SecurityGroup
      KeyName: !Ref KeyName
      ImageId: !Ref WebsideAmiId
      SubnetId: !Ref PrivateSubnet
      Tags:
        - Key: Name
          Value: !Ref EC22Name
        - Key: Application
          Value: !Ref "AWS::StackName"

Outputs:
  EC21:
    Description: EC1
    Value: !Ref EC2Instance1
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-EC2Ins1"
  EC22:
    Description: EC2
    Value: !Ref EC2Instance2
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-EC2Ins2"  