AWSTemplateFormatVersion: '2010-09-09'

Description: "Join all files yaml"

Parameters:
  VPCName:
    Description: VPC Name.
    Type: String 
    Default: VPC-G16

  BucketName:
    Description:  Bucket name the templates
    Type: String
    Default: https://templates-pro2-g16.s3.us-east-2.amazonaws.com

Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPCName: !Ref VPCName
      TemplateURL: !Sub ${BucketName}/vpc.yaml

